Fix build of libappstream-glib clients
With '#pragma once', __APPSTREAM_GLIB_H is never defined.

        In file included from /usr/include/libappstream-glib/appstream-glib.h:35:
        /usr/include/libappstream-glib/as-utils.h:11:2: error: #error "Only <appstream-glib.h> can be included directly."
         #error "Only <appstream-glib.h> can be included directly."
          ^~~~~

Fixes: 87b7483e ("Use '#pragma once' to avoid a lot of boilerplate")