Fix Win32 headers.
For some reason, with mingw-w64 64-bit builds, this was just a warning.
But building for 32-bit, linking was failing:

> libappstream-glib/as-self-test.c:99: undefined reference to `GetFullPathNameA'
> collect2: error: ld returned 1 exit status

Adding the appropriate header fixes both the warning and error (since
windows.h includes windef.h, it's actually a replacement).